name: Setup Gradle Wrapper
description: Checkout and chmod gradlew
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      shell: bash