package team.noweekend.core.navigator.extra

const val CREATE_VACATION_BUNDLE = "CREATE_VACATION_BUNDLE"
const val CREATE_VACATION_DAYS = "CREATE_VACATION_DAYS"
const val CREATE_VACATION_TRAVEL_STYLE = "CREATE_VACATION_TRAVEL_STYLE"
const val CREATE_VACATION_ACTIVITY_TYPE = "CREATE_VACATION_ACTIVITY_TYPE"
const val CREATE_VACATION_REST_PREFERENCE = "CREATE_VACATION_REST_PREFERENCE"
const val CREATE_VACATION_LEISURE_PREFERENCE = "CREATE_VACATION_LEISURE_PREFERENCE"
