name: NoWeekend CI

on:
  # Github Action에서 해당 workflow 수동 트리거 가능 옵션
  workflow_dispatch:
  pull_request:
    # feature/foo, feature/foo/bar/* 까지 대응
    branches: [ "feature/**", "hotfix/**", "release/**", "develop", "main"]

jobs:
  common-workflow-setup:
    name: common workflow setup
    uses: ./.github/workflows/common-setup.yaml
    secrets: inherit

  build:
    name: Gradle Build
    needs: common-workflow-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: jdk 17 setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: restore jks and keystore properties
        run: |
          mkdir -p ./keystore

          echo "${{ secrets.DEV_JKS_BASE64 }}" | base64 -d > ./keystore/dev.jks
          echo "${{ secrets.QA_JKS_BASE64 }}" | base64 -d > ./keystore/qa.jks
          echo "${{ secrets.PROD_JKS_BASE64 }}" | base64 -d > ./keystore/prod.jks

          echo "storeFileDev=./keystore/dev.jks" > keystore.properties
          echo "storeFileQa=./keystore/qa.jks" >> keystore.properties
          echo "storeFileProd=./keystore/prod.jks" >> keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug


#  ktlint:
#    name: Run Ktlint
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#
#      - name: Cache Gradle
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: gradle-${{ runner.os }}
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Run ktlint check
#        run: ./gradlew ktlintCheck